### ISSUE TITLE
三星GT-19507V Android5.0.1 crash

### ISSUE THREAD

**Issue by jackuhan** [asLody/legend#12]
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116] Throwing new exception 'length=643; index=51516434' with unexpected pending exception: java.lang.ArrayIndexOutOfBoundsException: length=77951; index=51516434
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at java.lang.String java.lang.reflect.ArtMethod.getNameNative!() (ArtMethod.java:-2)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at java.lang.String java.lang.reflect.ArtMethod.getMethodName(java.lang.reflect.ArtMethod) (ArtMethod.java:136)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at java.lang.String java.lang.reflect.Method.getName() (Method.java:139)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void com.lody.legend.HookManager.applyHooks(java.lang.Class) (HookManager.java:93)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void com.legend.demo.App.attachBaseContext(android.content.Context) (App.java:25)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[], boolean) (Method.java:-2)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:372)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(android.content.Context) (BootstrapApplication.java:248)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void android.app.Application.attach(android.content.Context) (Application.java:205)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at android.app.Application android.app.Instrumentation.newApplication(java.lang.Class, android.content.Context) (Instrumentation.java:1004)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at android.app.Application android.app.Instrumentation.newApplication(java.lang.ClassLoader, java.lang.String, android.content.Context) (Instrumentation.java:988)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at android.app.Application android.app.LoadedApk.makeApplication(boolean, android.app.Instrumentation) (LoadedApk.java:620)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5086)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void android.app.ActivityThread.access$1600(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:177)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1509)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void android.os.Looper.loop() (Looper.java:145)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5942)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[], boolean) (Method.java:-2)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:372)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1388)
07-08 17:57:21.060 23687-23687/com.legend.demo A/art: art/runtime/thread.cc:1116]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1183)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   native: #14 pc 000000e3  /system/framework/arm/boot.oat (Java_java_lang_reflect_ArtMethod_getNameNative__+82)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.ArtMethod.getNameNative!(Native method)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.ArtMethod.getMethodName(ArtMethod.java:136)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.Method.getName(Method.java:139)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at com.lody.legend.HookManager.applyHooks(HookManager.java:93)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at com.legend.demo.App.attachBaseContext(App.java:25)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.Method.invoke!(Native method)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.Method.invoke(Method.java:372)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:248)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.Application.attach(Application.java:205)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.Instrumentation.newApplication(Instrumentation.java:988)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.LoadedApk.makeApplication(LoadedApk.java:620)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5086)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.ActivityThread.access$1600(ActivityThread.java:177)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.os.Handler.dispatchMessage(Handler.java:102)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.os.Looper.loop(Looper.java:145)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.ActivityThread.main(ActivityThread.java:5942)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.Method.invoke!(Native method)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.Method.invoke(Method.java:372)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   native: #14 pc 000000e3  /system/framework/arm/boot.oat (Java_java_lang_reflect_ArtMethod_getNameNative__+82)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.ArtMethod.getNameNative!(Native method)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.ArtMethod.getMethodName(ArtMethod.java:136)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.Method.getName(Method.java:139)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at com.lody.legend.HookManager.applyHooks(HookManager.java:93)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at com.legend.demo.App.attachBaseContext(App.java:25)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.Method.invoke!(Native method)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.Method.invoke(Method.java:372)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:248)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.Application.attach(Application.java:205)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.Instrumentation.newApplication(Instrumentation.java:988)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.LoadedApk.makeApplication(LoadedApk.java:620)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5086)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.ActivityThread.access$1600(ActivityThread.java:177)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.os.Handler.dispatchMessage(Handler.java:102)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.os.Looper.loop(Looper.java:145)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at android.app.ActivityThread.main(ActivityThread.java:5942)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.Method.invoke!(Native method)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.reflect.Method.invoke(Method.java:372)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   native: #05 pc 000003d3  /system/framework/arm/boot.oat (Java_java_lang_Object_wait__+82)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Object.wait!(Native method)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   - waiting on <0x3e3977a6> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:137)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   - locked <0x3e3977a6> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Thread.run(Thread.java:818)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   native: #07 pc 0005f391  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void_)+72)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   native: #05 pc 000005f7  /system/framework/arm/boot.oat (Java_java_lang_Object_wait__JI+102)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Object.wait!(Native method)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   - waiting on <0x3150b5e7> (a java.lang.ref.ReferenceQueue)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Object.wait(Object.java:422)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   - locked <0x3150b5e7> (a java.lang.ref.ReferenceQueue)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:177)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Thread.run(Thread.java:818)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   native: #05 pc 000003d3  /system/framework/arm/boot.oat (Java_java_lang_Object_wait__+82)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Object.wait!(Native method)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   - waiting on <0x2e740594> (a java.lang.Daemons$FinalizerWatchdogDaemon)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:243)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   - locked <0x2e740594> (a java.lang.Daemons$FinalizerWatchdogDaemon)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:215)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Thread.run(Thread.java:818)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   native: #07 pc 0005f391  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void_)+72)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   native: #05 pc 000003d3  /system/framework/arm/boot.oat (Java_java_lang_Object_wait__+82)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Object.wait!(Native method)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   - waiting on <0x0591a83d> (a java.lang.Daemons$HeapTrimmerDaemon)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:314)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   - locked <0x0591a83d> (a java.lang.Daemons$HeapTrimmerDaemon)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Thread.run(Thread.java:818)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   native: #03 pc 000003d3  /system/framework/arm/boot.oat (Java_dalvik_system_VMRuntime_waitForConcurrentGCRequest__+82)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Daemons$GCDaemon.run(Daemons.java:334)
07-08 17:57:21.191 23687-23687/com.legend.demo A/art: art/runtime/runtime.cc:284]   at java.lang.Thread.run(Thread.java:818)
07-08 17:57:21.281 297-297/? I/DEBUG: Abort message: 'art/runtime/thread.cc:1116] Throwing new exception 'length=643; index=51516434' with unexpected pending exception: java.lang.ArrayIndexOutOfBoundsException: length=77951; index=51516434'
07-08 17:57:21.901 917-23741/? W/ActivityManager: Exception thrown during pause
                                                  android.os.DeadObjectException
                                                      at android.os.BinderProxy.transactNative(Native Method)
                                                      at android.os.BinderProxy.transact(Binder.java:496)
                                                      at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:766)
                                                      at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1199)
                                                      at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3699)
                                                      at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3513)
                                                      at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:3450)
                                                      at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:14836)
                                                      at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:14709)
                                                      at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:15475)
                                                      at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:14983)
                                                      at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
07-08 17:57:21.921 917-1033/? W/WindowManager: Failed looking up window
                                               java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@21e4997c does not exist
                                                   at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:10500)
                                                   at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:10491)
                                                   at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:3319)
                                                   at com.android.server.wm.Session.remove(Session.java:194)
                                                   at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3236)
                                                   at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6169)
                                                   at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3607)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:145)
                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                   at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by zhangyiran** [comment]
我已经修复了，你更新代码试试
