### ISSUE TITLE
在Android 7.0上hook失败

### ISSUE THREAD

**Issue by zanyz106** [asLody/legend#17]
12-05 12:10:26.005 13676-13676/? E/Legend-Log: [---] Error to Load Hook Method From : Application_onCreate.
12-05 12:10:26.005 13676-13676/? W/System.err: java.lang.IllegalStateException: Cannot create backup method from :: public void android.app.Application.onCreate()
12-05 12:10:26.005 13676-13676/? W/System.err:     at com.lody.legend.art.ArtMethod.backup(ArtMethod.java:134)
12-05 12:10:26.005 13676-13676/? W/System.err:     at com.lody.legend.HookManager.hookMethodArt(HookManager.java:199)
12-05 12:10:26.005 13676-13676/? W/System.err:     at com.lody.legend.HookManager.hookMethod(HookManager.java:136)
12-05 12:10:26.005 13676-13676/? W/System.err:     at com.lody.legend.HookManager.applyHooks(HookManager.java:91)
12-05 12:10:26.006 13676-13676/? W/System.err:     at com.legend.demo.App.attachBaseContext(App.java:27)
12-05 12:10:26.006 13676-13676/? W/System.err:     at android.app.Application.attach(Application.java:189)
12-05 12:10:26.006 13676-13676/? W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
12-05 12:10:26.006 13676-13676/? W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:992)
12-05 12:10:26.006 13676-13676/? W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
12-05 12:10:26.006 13676-13676/? W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5335)
12-05 12:10:26.006 13676-13676/? W/System.err:     at android.app.ActivityThread.-wrap2(ActivityThread.java)
12-05 12:10:26.006 13676-13676/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
12-05 12:10:26.006 13676-13676/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-05 12:10:26.006 13676-13676/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
12-05 12:10:26.006 13676-13676/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
12-05 12:10:26.006 13676-13676/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-05 12:10:26.006 13676-13676/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
12-05 12:10:26.006 13676-13676/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by yunshouhu** [comment]
什么时候支持android7.0以上？android7.0的class ArtMethod结构体中没有成员域entry_point_from_interpreter_了,怎么破？谢谢。
