### ISSUE TITLE
android 7.0 is not support

### ISSUE THREAD

**Issue by cding24** [asLody/legend#37]
09-17 14:11:56.843 6231-6231/com.dodola.rocoosample.runtimefix W/System.err: java.lang.SecurityException: Can not make a java.lang.reflect.Method constructor accessible
09-17 14:11:56.843 6231-6231/com.dodola.rocoosample.runtimefix W/System.err:     at java.lang.reflect.AccessibleObject.setAccessible0(AccessibleObject.java:133)
09-17 14:11:56.844 6231-6231/com.dodola.rocoosample.runtimefix W/System.err:     at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:89)
09-17 14:11:56.844 6231-6231/com.dodola.rocoosample.runtimefix W/System.err:     at com.lody.legend.art.ArtMethod.backup(ArtMethod.java:109)
09-17 14:11:56.844 6231-6231/com.dodola.rocoosample.runtimefix W/System.err:     at com.lody.legend.HookManager.hookMethodArt(HookManager.java:202)
09-17 14:11:56.844 6231-6231/com.dodola.rocoosample.runtimefix W/System.err:     at com.lody.legend.HookManager.hookMethod(HookManager.java:137)

**Comment by cding24** [comment]
是不是这个项目现在不维护更新了

**Comment by weimingjue** [comment]
我也很诧异，但是第一句不是说了吗：改到whale这个项目下了，应该是原理完全不同所以换了
